# Generated by Django 6.0 on 2025-12-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('queue_number', 'time_joined', 'hospital')},
        ),
    ]
