# Generated by Django 6.0 on 2025-12-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_queue_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='queue',
            name='queue_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('hospital', 'queue_number', 'time_joined'), name='unique_queue_number_per_hospital'),
        ),
    ]
