# Generated by Django 6.0 on 2025-12-23 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_queue_unique_together_alter_queue_queue_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
