# Generated by Django 6.0 on 2025-12-24 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_hospital', to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.patient'),
        ),
    ]
