# Generated by Django 6.0 on 2025-12-24 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patient_hospital_alter_queue_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='api.hospital'),
        ),
    ]
